FROM python:3.5

RUN pip install pyinstaller

RUN mkdir /opt/cook
WORKDIR /opt/cook

COPY requirements.txt /opt/cook/
RUN pip install -r requirements.txt

COPY . /opt/cook

CMD ["pyinstaller", "-F", "-n", "cook-executor-docker", "-p", "cook", "cook/__main__.py"]
