name: Cook Scheduler integration tests with Cook Executor and Docker

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - 'build**'
      - kubernetes_integration
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.x'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup environment variables
        run: |
          echo /home/runner/.local/bin >> $GITHUB_PATH
          echo "PYTEST_ADDOPTS=--color=yes" >> $GITHUB_ENV
      - name: Run integration tests
        run: |
          sudo ./travis/install_mesos.sh
          cd integration && ./travis/prepare_integration.sh
          cd .. && export PYTHONPATH=$PWD/jobclient/python
          cd integration && ./travis/run_integration.sh --executor=cook --image=python:3.5
