name: Cook Scheduler, CLI, and JobClient unit tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - 'build**'
      - kubernetes_integration
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.x'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup tests
        run: |
          ./cli/travis/setup.sh
          cd scheduler && ./travis/setup.sh
      - name: Run JobClient Java unit tests
        run: cd ./jobclient/java && mvn test 
      - name: Run JobClient Python unit tests
        run: cd ./jobclient/python && python -m pytest
        env:
          PYTEST_ADDOPTS: --color=yes
      - name: CLI unit tests
        run: cd ./cli && python -m pytest
        env:
          PYTEST_ADDOPTS: --color=yes
      - name: Scheduler Unit tests
        run: cd ./scheduler && lein with-profile +test test :all-but-benchmark
