name: 'Cook Scheduler, CLI, and JobClient unit tests'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - 'build**'
      - kubernetes_integration
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Setup tests
        run: |
          ./cli/travis/setup.sh
          cd scheduler && ./travis/setup.sh
      - name: Run unit tests
        run: |
          pushd ../jobclient/java && mvn test
          popd && pushd ../jobclient/python && python -m pytest
          popd && pushd ../cli && python -m pytest
          popd && lein with-profile +test test :all-but-benchmark
